/**
 * Style Dictionary v5 Configuration
 *
 * Reads DTCG tokens from design-tokens/tokens.json (generated by css-to-dtcg.js)
 * and produces multi-platform outputs in build/.
 *
 * Platforms:
 *   - css:     CSS custom properties (BDS naming convention)
 *   - js:      ES module + TypeScript types
 *   - ios:     Swift enum (placeholder for future)
 *   - android: Android XML resources (placeholder for future)
 *
 * Run: npx style-dictionary build --config sd.config.mjs
 */

import StyleDictionary from 'style-dictionary';

// ─── Custom Transform: DTCG path → BDS CSS variable name ────────────
//
// Converts the DTCG dot-path back to BDS CSS custom property names:
//   color.text.primary      → --_color---text--primary    (semantic)
//   grayscale.dark           → --grayscale--dark           (primitive)
//   font-size.300            → --font-size--300            (primitive)
//   typography.heading.large → --_typography---heading--large (semantic)

StyleDictionary.registerTransform({
  name: 'name/bds-css',
  type: 'name',
  transform: (token) => {
    const path = token.path;
    if (path.length === 0) return '';

    // Use $extensions metadata to determine semantic vs primitive
    const isSemantic = token.$extensions?.['com.brikdesigns.bds']?.semantic === true;

    if (isSemantic && path.length >= 2) {
      // Semantic tokens: _category---rest--parts
      const category = path[0];
      const rest = path.slice(1).join('--');
      return `_${category}---${rest}`;
    }

    // Primitive tokens: category--name
    return path.join('--');
  },
});

// ─── Custom Transform: DTCG path → Swift/Kotlin name ────────────────
StyleDictionary.registerTransform({
  name: 'name/bds-camel',
  type: 'name',
  transform: (token) => {
    // Convert path segments to camelCase
    // color.text.primary → colorTextPrimary
    return token.path
      .map((segment, i) => {
        const clean = segment.replace(/-(\w)/g, (_, c) => c.toUpperCase());
        if (i === 0) return clean;
        return clean.charAt(0).toUpperCase() + clean.slice(1);
      })
      .join('');
  },
});

// ─── Platform Configurations ─────────────────────────────────────────

export default {
  source: ['design-tokens/tokens.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      transforms: ['name/bds-css'],
      prefix: '',
      buildPath: 'build/css/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            outputReferences: true,
            selector: ':root',
          },
        },
      ],
    },

    js: {
      transformGroup: 'js',
      transforms: ['name/bds-camel'],
      buildPath: 'build/js/',
      files: [
        {
          destination: 'tokens.mjs',
          format: 'javascript/es6',
        },
        {
          destination: 'tokens.d.ts',
          format: 'typescript/es6-declarations',
        },
      ],
    },

    ios: {
      transformGroup: 'ios-swift',
      transforms: ['name/bds-camel'],
      buildPath: 'build/ios/',
      files: [
        {
          destination: 'DesignTokens.swift',
          format: 'ios-swift/enum.swift',
          options: {
            className: 'BDSTokens',
          },
        },
      ],
    },

    android: {
      transformGroup: 'android',
      buildPath: 'build/android/',
      files: [
        {
          destination: 'colors.xml',
          format: 'android/colors',
          filter: (token) => token.$type === 'color',
        },
        {
          destination: 'dimens.xml',
          format: 'android/dimens',
          filter: (token) => token.$type === 'dimension',
        },
        {
          destination: 'font_dimens.xml',
          format: 'android/fontDimens',
          filter: (token) =>
            token.$type === 'fontWeight' ||
            token.$type === 'number',
        },
      ],
    },
  },
};
