/**
 * Style Dictionary Config — Dark Mode
 *
 * Reads dark-mode DTCG tokens from design-tokens/tokens-figma-dark.json
 * (generated by: node scripts/flatten-tokens-studio.js --mode color=dark --output design-tokens/tokens-figma-dark.json)
 * and outputs CSS custom properties scoped to [data-theme="dark"].
 *
 * Only outputs semantic color tokens (background, text, border, surface, page)
 * since primitives (grayscale, spacing, typography) don't change between modes.
 *
 * Run: npm run build:sd-dark
 */

import { register } from '@tokens-studio/sd-transforms';
import StyleDictionary from 'style-dictionary';

register(StyleDictionary);

// Semantic color groups — only these change between light and dark modes
const SEMANTIC_GROUPS = ['background', 'text', 'border', 'surface', 'page'];

export default {
  log: {
    // Suppress "filtered out token references" warning — expected because
    // dark mode semantic tokens reference primitives that are defined in
    // the light mode file (always loaded first in the cascade).
    warnings: 'disabled',
  },
  source: ['design-tokens/tokens-figma-dark.json'],
  preprocessors: ['tokens-studio'],
  platforms: {
    css: {
      transformGroup: 'tokens-studio',
      transforms: ['name/kebab'],
      buildPath: 'build/figma/css/',
      files: [
        {
          destination: 'variables-dark.css',
          format: 'css/variables',
          filter: (token) => SEMANTIC_GROUPS.includes(token.path[0]),
          options: {
            outputReferences: true,
            selector: ':root[data-theme="dark"]',
          },
        },
      ],
    },
  },
};
