/**
 * token-bridge.mjs — derive the old-name -> new-name alias layer for the System
 * ID migration (ADR-043, brik-bds#2670) from a built canonical dist/tokens.css.
 *
 * For every name in the frozen legacy snapshot the bridge declares
 * `--old: var(--bds-new)` in EVERY selector block where `--bds-new` is declared,
 * not only `:root`. A custom property that aliases another resolves where it is
 * declared, so an alias at `:root` alone would hand a consumer reading
 * `--text-primary` under `[data-theme="dark"]` / `.theme-brand-brik` /
 * `[data-mode-*]` the light root value. Re-declaring it per block makes
 * old name === new name in every scope.
 */

import { RENAMED_KNOBS, declarationMap, prefixName, PREFIX, readLegacy } from './bds-prefix.mjs';

const HEADER = `/*
 * @brikdesigns/bds — System ID prefix bridge (GENERATED — do not edit)
 *
 * ADR-043 moved every BDS Primitive and Semantic token onto the System ID
 * prefix: \`--text-primary\` is now \`--bds-text-primary\`. This file aliases each
 * pre-migration name to its \`--bds-\` name so a consumer still reading the old
 * names keeps resolving. It is appended to dist/tokens.css (so
 * \`@brikdesigns/bds/tokens.css\` carries it) and published standalone as
 * \`@brikdesigns/bds/prefix-bridge.css\`.
 *
 * Each alias is re-declared in every selector block where its \`--bds-\` name is
 * declared (:root, :root[data-theme="dark"], .theme-brand-brik, [data-mode-*]),
 * so the old name resolves to the same value as the new one in every scope.
 *
 * The 54 word-step colour names (\`--color-poppy-dark\`) no longer exist in the
 * canonical tokens (ADR-043 section 4). They live only here, aliasing the
 * numeric \`--bds-color-{family}-{step}\` they always pointed at.
 *
 * KNOWN LIMIT (ADR-043 section 6): the bridge covers consumer READS of the old
 * names. It does not cover consumer OVERRIDES. A consumer that re-declares an
 * old name (\`--text-primary: red\`) changes only the alias; every BDS component
 * now reads the \`--bds-\` name and will not see it. Override the \`--bds-\` name.
 *
 * Generated by: npm run build:token-bridge (scripts/build-token-bridge.mjs).
 * Delete when all six consumers are off the old names (separate sub-issue).
 */
`;

/**
 * @param {string} canonicalCss  dist/tokens.css WITHOUT the bridge section
 * @returns {{ css: string, aliasCount: number, blockCount: number, missing: string[] }}
 */
export function generateBridge(canonicalCss, legacy = readLegacy()) {
  const declared = declarationMap(canonicalCss);
  const aliases = new Map(); // context -> [old, new][]
  const missing = [];
  let aliasCount = 0;

  for (const oldName of legacy.names) {
    if (oldName.startsWith(PREFIX)) continue; // already a Component-tier `--bds-*` name
    const newName = prefixName(legacy.wordSteps[oldName] ?? oldName);
    const homes = [...declared].filter(([, names]) => names.has(newName)).map(([context]) => context);
    if (homes.length === 0) {
      missing.push(`${oldName} -> ${newName}`);
      continue;
    }
    aliasCount += 1;
    for (const context of homes) {
      if (!aliases.has(context)) aliases.set(context, []);
      aliases.get(context).push([oldName, newName]);
    }
  }

  const blocks = [];
  for (const [context, pairs] of aliases) {
    if (context.includes(' >> ')) throw new Error(`bridge: nested context not supported: ${context}`);
    const lines = pairs.map(([o, n]) => `  ${o}: var(${n});`);
    blocks.push(`${context} {\n${lines.join('\n')}\n}`);
  }

  // Component knobs renamed off a reserved stem (ADR-043 section 5). Not
  // declared in dist/tokens.css, so they alias at :root only.
  const knobLines = Object.entries(RENAMED_KNOBS).map(([o, n]) => `  ${o}: var(${n});`);
  const knobBlock = `/* Component knobs renamed off a reserved stem (ADR-043 section 5). */\n:root {\n${knobLines.join('\n')}\n}`;
  aliasCount += Object.keys(RENAMED_KNOBS).length;

  const css = `${HEADER}\n${blocks.join('\n\n')}\n\n${knobBlock}\n`;
  return { css, aliasCount, blockCount: aliases.size + 1, missing };
}
