#!/usr/bin/env node
/**
 * gen-logos.mjs — Bundled brand-logo registry for BDS <Logo>.
 *
 * Reads the full-color source marks in `assets/logo-{set}-{name}.svg`, strips
 * the root `width`/`height` (so CSS owns sizing — the `viewBox` is preserved),
 * and emits `components/ui/Logo/logos.generated.ts`: an inline-SVG map plus a
 * `const` name tuple per set. The <Logo> component reads this at module load,
 * so logos resolve synchronously with NO runtime fetch — the same offline
 * contract as the <Icon> Phosphor subset (brik-bds#1002), but for multi-fill
 * brand art that must NOT be recolored.
 *
 * Unlike <Icon> (monochrome, recolorable) and ServiceTag (mask-recolored), a
 * brand logo renders exactly as authored — brand guidelines lock the color.
 *
 * Sets are inferred from the filename prefix after `logo-`:
 *   logo-cc-*          → credit-card   (Visa, Mastercard, Stripe, …)
 *   logo-third-party-* → integration   (Google, Notion, Figma, …)
 *   logo-client-*      → client        (per-onboarded-client marks)
 *
 * Modes:
 *   node scripts/gen-logos.mjs           # write the registry
 *   node scripts/gen-logos.mjs --check   # fail if committed file is stale (CI drift gate)
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');
const ASSETS_DIR = path.join(REPO_ROOT, 'assets');
const OUTPUT_PATH = path.join(REPO_ROOT, 'components', 'ui', 'Logo', 'logos.generated.ts');

// Filename prefix (after `logo-`) → public set name. Order controls emit order.
const PREFIX_TO_SET = [
  ['cc-', 'credit-card'],
  ['third-party-', 'integration'],
  ['client-', 'client'],
];

// Public set name → the tuple/const identifier emitted for it.
const SET_CONST = {
  'credit-card': 'CREDIT_CARD_LOGOS',
  integration: 'INTEGRATION_LOGOS',
  client: 'CLIENT_LOGOS',
};

/** Strip root-element width/height so CSS sizes the mark; keep the viewBox. */
function normalizeSvg(raw) {
  const svg = raw.trim();
  return svg.replace(/^<svg\b[^>]*>/, (openTag) =>
    openTag.replace(/\s+(width|height)="[^"]*"/g, ''),
  );
}

function collect() {
  const files = fs
    .readdirSync(ASSETS_DIR)
    .filter((f) => f.startsWith('logo-') && f.endsWith('.svg'))
    .sort();

  const svgs = {}; // registry key (`${prefix}${name}`) → inline svg
  const sets = { 'credit-card': [], integration: [], client: [] };

  for (const file of files) {
    const slug = file.slice('logo-'.length, -'.svg'.length); // e.g. "cc-visa"
    const match = PREFIX_TO_SET.find(([prefix]) => slug.startsWith(prefix));
    if (!match) {
      throw new Error(
        `Unknown logo set for "${file}" — expected a logo-{cc|third-party|client}-* prefix.`,
      );
    }
    const [prefix, set] = match;
    const name = slug.slice(prefix.length); // e.g. "visa"
    svgs[slug] = normalizeSvg(fs.readFileSync(path.join(ASSETS_DIR, file), 'utf8'));
    sets[set].push(name);
  }
  return { svgs, sets };
}

function render({ svgs, sets }) {
  const banner = `// AUTO-GENERATED by scripts/gen-logos.mjs — DO NOT EDIT BY HAND.
// Source: assets/logo-*.svg. Regenerate: \`npm run gen:logos\`.
// Full-color brand marks, bundled inline so <Logo> resolves offline with no
// runtime fetch. Never recolored — brand guidelines own the color.
`;

  const setBlocks = Object.entries(sets)
    .map(([set, names]) => {
      const items = names.map((n) => `'${n}'`).join(', ');
      return `export const ${SET_CONST[set]} = [${items}] as const;`;
    })
    .join('\n');

  const svgEntries = Object.entries(svgs)
    .map(([key, svg]) => `  ${JSON.stringify(key)}: ${JSON.stringify(svg)},`)
    .join('\n');

  return `${banner}
${setBlocks}

/** Registry key → inline SVG markup. Key is \`{setPrefix}-{name}\` (e.g. \`cc-visa\`). */
export const LOGO_SVGS: Record<string, string> = {
${svgEntries}
};
`;
}

const check = process.argv.includes('--check');
const output = render(collect());

if (check) {
  const current = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, 'utf8') : '';
  if (current !== output) {
    console.error(
      'logos.generated.ts is stale. Run `npm run gen:logos` and commit the result.',
    );
    process.exit(1);
  }
  console.log('gen-logos --check: registry is up to date.');
} else {
  fs.writeFileSync(OUTPUT_PATH, output);
  const count = Object.keys(collect().svgs).length;
  console.log(`gen-logos: wrote ${count} logos → ${path.relative(REPO_ROOT, OUTPUT_PATH)}`);
}
