import { useEffect } from 'react';
import type { Preview, Decorator } from '@storybook/react';
import type { ThemeNumber } from '../tokens';

// Font Awesome 6 — prevent auto-CSS injection, import CSS manually
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

// Import extracted token-only CSS (fonts + custom properties)
// Generated by: npm run extract-tokens
import '../tokens/fonts.css';
import '../tokens/webflow-tokens.css';
import '../tokens/themes.css';
// Import overrides AFTER Webflow CSS to fix Storybook UI conflicts
import './storybook-overrides.css';

/**
 * Theme wrapper component — centers story content within the
 * themed preview area. Background/text colors come from the
 * body-level theme classes (applied by the decorator).
 */
function ThemeWrapper({
  children,
  themeNumber
}: {
  children: React.ReactNode;
  themeNumber: ThemeNumber;
}) {
  return (
    <div
      className={`body theme-${themeNumber}`}
      style={{
        padding: 'var(--_space---md)',
        minHeight: '100%',
        width: '100%',
        boxSizing: 'border-box' as const,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      {children}
    </div>
  );
}

/**
 * Theme decorator — applies theme classes to the preview <body>
 * for immersive theming (docs page bg, text, args table all respond
 * to the selected theme), then wraps stories in ThemeWrapper.
 */
const withTheme: Decorator = (Story, context) => {
  const themeNumber = (context.globals.themeNumber || 'brik') as ThemeNumber;

  // Apply theme classes to the preview iframe <body> so CSS variables
  // cascade to the entire page — docs wrapper, headings, args table, etc.
  useEffect(() => {
    const body = document.body;
    // Strip any previous theme class
    body.className = body.className.replace(/\btheme-\S+/g, '');
    // .body.theme-X matches our CSS selectors in themes.css
    body.classList.add('body', `theme-${themeNumber}`);
  }, [themeNumber]);

  return (
    <ThemeWrapper themeNumber={themeNumber}>
      <Story />
    </ThemeWrapper>
  );
};

const preview: Preview = {
  globalTypes: {
    themeNumber: {
      name: 'Theme',
      description: 'BDS theme (bundled color, typography, spacing)',
      defaultValue: 'brik',
      toolbar: {
        icon: 'paintbrush',
        items: [
          // Brik
          { value: 'brik', title: 'Brik: Brik Light (Default)' },
          { value: 'brik-dark', title: 'Brik: Brik Dark' },
          // Expressive
          { value: '1', title: '1: Peach (Open Sans)' },
          { value: '2', title: '2: Pastel (Source Sans)' },
          { value: '3', title: '3: Luxury (Hind)' },
          { value: '4', title: '4: Vibrant (Playfair Display)' },
          // Modern
          { value: '5', title: '5: White (Open Sans)' },
          { value: '6', title: '6: Black (Geist Mono)' },
          { value: '7', title: '7: Blue (Source Sans)' },
          { value: '8', title: '8: Yellow (Hind)' },
        ],
        dynamicTitle: true,
      },
    },
  },
  decorators: [withTheme],
  parameters: {
    options: {
      storySort: {
        order: ['Getting Started', 'Components', '*', 'Theme'],
      },
    },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    layout: 'fullscreen', // ThemeWrapper handles padding + bg
    backgrounds: {
      disable: true, // Managed by theme
    },
    docs: {
      toc: true,
      source: {
        type: 'dynamic',
        excludeDecorators: true,
        format: false,
      },
    },
  },
};

export default preview;
