import type { Preview, Decorator } from '@storybook/react';
import type { ThemeNumber } from '../tokens';

// Font Awesome 6 — prevent auto-CSS injection, import CSS manually
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

// Import extracted token-only CSS (fonts + custom properties)
// Generated by: npm run extract-tokens
import '../tokens/fonts.css';
import '../tokens/webflow-tokens.css';
import '../tokens/themes.css';
// Import overrides AFTER Webflow CSS to fix Storybook UI conflicts
import './storybook-overrides.css';

/**
 * Theme wrapper component that applies Webflow theme classes
 * Uses a div with both 'body' and 'theme-X' classes to match
 * Webflow's .body.theme-X selector pattern
 */
function ThemeWrapper({
  children,
  themeNumber
}: {
  children: React.ReactNode;
  themeNumber: ThemeNumber;
}) {
  return (
    <div
      className={`body theme-${themeNumber}`}
      style={{
        border: 'none',
        borderRadius: 0,
        backgroundColor: 'var(--_color---page--primary)',
        color: 'var(--_color---text--primary)',
        padding: 'var(--_space---lg)',
        // Fill entire story canvas so theme bg covers the full area
        minHeight: '100%',
        width: '100%',
        boxSizing: 'border-box' as const,
      }}
    >
      {children}
    </div>
  );
}

/**
 * Theme decorator - wraps all stories in ThemeWrapper
 * and adds toolbar controls for theme switching
 */
const withTheme: Decorator = (Story, context) => {
  const themeNumber = (context.globals.themeNumber || 'brik') as ThemeNumber;

  return (
    <ThemeWrapper themeNumber={themeNumber}>
      <Story />
    </ThemeWrapper>
  );
};

const preview: Preview = {
  globalTypes: {
    themeNumber: {
      name: 'Theme',
      description: 'BDS theme (bundled color, typography, spacing)',
      defaultValue: 'brik',
      toolbar: {
        icon: 'paintbrush',
        items: [
          // Brik
          { value: 'brik', title: 'Brik: Brik Light (Default)' },
          { value: 'brik-dark', title: 'Brik: Brik Dark' },
          // Expressive
          { value: '1', title: '1: Peach (Open Sans)' },
          { value: '2', title: '2: Pastel (Source Sans)' },
          { value: '3', title: '3: Luxury (Hind)' },
          { value: '4', title: '4: Vibrant (Playfair Display)' },
          // Modern
          { value: '5', title: '5: White (Open Sans)' },
          { value: '6', title: '6: Black (Geist Mono)' },
          { value: '7', title: '7: Blue (Source Sans)' },
          { value: '8', title: '8: Yellow (Hind)' },
        ],
        dynamicTitle: true,
      },
    },
  },
  decorators: [withTheme],
  parameters: {
    options: {
      storySort: {
        order: ['Getting Started', 'Components', '*', 'Theme'],
      },
    },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    layout: 'fullscreen', // ThemeWrapper handles padding + bg
    backgrounds: {
      disable: true, // Managed by theme
    },
    docs: {
      toc: true,
      source: {
        type: 'dynamic',
        excludeDecorators: true,
        format: false,
      },
    },
  },
};

export default preview;
